service: mintable-lite

provider:
  name: aws
  runtime: nodejs16.x


# resources:
#   Resources:
#     TacosDB:
#       Type: 'AWS::DynamoDB::Table'
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: id
#             AttributeType: S
#           -
#             AttributeName: name
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: id
#             KeyType: HASH
#           -
#             AttributeName: name
#             KeyType: RANGE
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: TacoGallery

functions:
  mint:
    handler: dist/handler.mint
    events:
      - http:
          path: mint
          method: post
  get:
    handler: dist/handler.get
    events:
      - http:
          path: get
          method: post
  list:
    handler: dist/handler.list
    events:
      - http:
          path: list
          method: post

plugins:
  #- serverless-dynamodb-local
  - serverless-offline

# custom:
#   serverless-offline:
#     babelOptions:
#       presets: ["es2015"]